/**
 * V2 Types Index
 *
 * Re-exports all V2 types for convenient importing.
 */

// Common types
export type {
	MessageAndSwipe,
	TimeDelta,
	LocationState,
	WeatherCondition,
	DaylightPhase,
	BuildingType,
	ClimateForecast,
	TensionLevel,
	TensionDirection,
	TensionType,
	RelationshipStatus,
	OutfitSlot,
	CharacterOutfit,
} from './common';

export {
	TENSION_LEVELS,
	TENSION_TYPES,
	TENSION_DIRECTIONS,
	RELATIONSHIP_STATUSES,
	OUTFIT_SLOTS,
	DAYS_OF_WEEK,
	isValidTensionLevel,
	isValidTensionType,
	isValidTensionDirection,
	isValidRelationshipStatus,
	isValidOutfitSlot,
	createEmptyOutfit,
	createEmptyLocationState,
	// Moment utilities for time handling
	durationToTimeDelta,
	timeDeltaToDuration,
	addTimeDelta,
	serializeMoment,
	deserializeMoment,
	zeroTimeDelta,
	extractedDateTimeToMoment,
	extractedDateTimeToIsoString,
} from './common';

// Subject types
export type { Subject } from './subject';

export {
	SUBJECTS,
	SUBJECT_GROUPS,
	MILESTONE_WORTHY_SUBJECTS,
	isValidSubject,
	isMilestoneWorthy,
	getSubjectGroup,
} from './subject';

// Event types
export type {
	EventKind,
	TimeSubkind,
	LocationSubkind,
	CharacterSubkind,
	RelationshipSubkind,
	ChapterSubkind,
	BaseEvent,
	TimeInitialEvent,
	TimeDeltaEvent,
	TimeEvent,
	LocationMovedEvent,
	LocationPropAddedEvent,
	LocationPropRemovedEvent,
	LocationEvent,
	ForecastGeneratedEvent,
	CharacterAppearedEvent,
	CharacterDepartedEvent,
	CharacterProfileSetEvent,
	CharacterPositionChangedEvent,
	CharacterActivityChangedEvent,
	CharacterMoodAddedEvent,
	CharacterMoodRemovedEvent,
	CharacterOutfitChangedEvent,
	CharacterPhysicalAddedEvent,
	CharacterPhysicalRemovedEvent,
	CharacterEvent,
	RelationshipFeelingAddedEvent,
	RelationshipFeelingRemovedEvent,
	RelationshipSecretAddedEvent,
	RelationshipSecretRemovedEvent,
	RelationshipWantAddedEvent,
	RelationshipWantRemovedEvent,
	RelationshipStatusChangedEvent,
	RelationshipSubjectEvent,
	RelationshipEvent,
	TopicToneEvent,
	TensionEvent,
	NarrativeDescriptionEvent,
	ChapterEndedEvent,
	ChapterDescribedEvent,
	ChapterEvent,
	Event,
	KindAndSubkind,
} from './event';

export {
	isTimeEvent,
	isTimeInitialEvent,
	isTimeDeltaEvent,
	isLocationEvent,
	isLocationMovedEvent,
	isLocationPropAddedEvent,
	isLocationPropRemovedEvent,
	isForecastGeneratedEvent,
	isCharacterEvent,
	isCharacterAppearedEvent,
	isCharacterDepartedEvent,
	isCharacterProfileSetEvent,
	isCharacterPositionChangedEvent,
	isCharacterActivityChangedEvent,
	isCharacterMoodAddedEvent,
	isCharacterMoodRemovedEvent,
	isCharacterOutfitChangedEvent,
	isCharacterPhysicalAddedEvent,
	isCharacterPhysicalRemovedEvent,
	isRelationshipEvent,
	isRelationshipFeelingAddedEvent,
	isRelationshipFeelingRemovedEvent,
	isRelationshipSecretAddedEvent,
	isRelationshipSecretRemovedEvent,
	isRelationshipWantAddedEvent,
	isRelationshipWantRemovedEvent,
	isRelationshipStatusChangedEvent,
	isRelationshipSubjectEvent,
	isTopicToneEvent,
	isTensionEvent,
	isNarrativeDescriptionEvent,
	isChapterEvent,
	isChapterEndedEvent,
	isChapterDescribedEvent,
	isDirectionalRelationshipEvent,
	getRelationshipPair,
	matchesKindAndSubkind,
} from './event';

// Snapshot and projection types
export type {
	CharacterState,
	RelationshipAttitude,
	RelationshipState,
	SceneState,
	Snapshot,
	Projection,
	NarrativeEvent,
	NarrativeEventSubject,
	Chapter,
} from './snapshot';

export {
	createEmptyCharacterState,
	createEmptyAttitude,
	createEmptyRelationshipState,
	createEmptySceneState,
	createEmptySnapshot,
	createProjectionFromSnapshot,
	createSnapshotFromProjection,
	getRelationshipKey,
	parseRelationshipKey,
	sortPair,
	cloneSnapshot,
	cloneProjection,
} from './snapshot';

// Extraction types
export type {
	ExtractedDateTime,
	ExtractedInitialTime,
	ExtractedInitialLocation,
	ExtractedInitialProps,
	ExtractedInitialClimate,
	ExtractedCharactersPresent,
	ExtractedCharacterOutfits,
	ExtractedInitialRelationships,
	ExtractedInitialTopicTone,
	ExtractedInitialTension,
	ExtractedTimeChange,
	ExtractedLocationChange,
	ExtractedPropsChange,
	ExtractedPropsConfirmation,
	ExtractedClimateChange,
	ExtractedCharacterPresenceChange,
	ExtractedOutfitChange,
	ExtractedMoodChange,
	ExtractedPositionChange,
	ExtractedActivityChange,
	ExtractedPhysicalChange,
	ExtractedWantsChange,
	ExtractedFeelingsChange,
	ExtractedSecretsChange,
	ExtractedStatusChange,
	ExtractedSubjects,
	ExtractedSubjectsConfirmation,
	ExtractedTopicToneChange,
	ExtractedTensionChange,
	ExtractedNarrativeDescription,
	ExtractedMilestoneDescription,
	ExtractedChapterEnded,
	ExtractedChapterDescription,
	ExtractedCharacterChanges,
	ExtractedAttitudeChanges,
} from './extraction';

export {
	hasReasoning,
	extractionIndicatesChange,
	extractionHasListChanges,
	extractionHasOutfitChanges,
} from './extraction';
