/**
 * V2 Subject Types
 *
 * Subjects replace EventTypes - they represent what happened in an interaction.
 * A subject becomes a milestone when it has a description (generated by LLM).
 */

/**
 * Subject categories for interaction types.
 * These are used by relationship extractors to identify interaction patterns.
 */
export type Subject =
	// Conversation & Social
	| 'conversation'
	| 'confession'
	| 'argument'
	| 'negotiation'

	// Discovery & Information
	| 'discovery'
	| 'secret_shared'
	| 'secret_revealed'

	// Emotional
	| 'emotional'
	| 'emotionally_intimate'
	| 'supportive'
	| 'rejection'
	| 'comfort'
	| 'apology'
	| 'forgiveness'

	// Bonding & Connection
	| 'laugh'
	| 'gift'
	| 'compliment'
	| 'tease'
	| 'flirt'
	| 'date'
	| 'i_love_you'
	| 'sleepover'
	| 'shared_meal'
	| 'shared_activity'

	// Intimacy Levels (granular for romantic RP)
	| 'intimate_touch'
	| 'intimate_kiss'
	| 'intimate_embrace'
	| 'intimate_heated'

	// Sexual Activity (activity-based granularity)
	| 'intimate_foreplay'
	| 'intimate_oral'
	| 'intimate_manual'
	| 'intimate_penetrative'
	| 'intimate_climax'

	// Action & Physical
	| 'action'
	| 'combat'
	| 'danger'

	// Decisions & Commitments
	| 'decision'
	| 'promise'
	| 'betrayal'
	| 'lied'

	// Life Events
	| 'exclusivity'
	| 'marriage'
	| 'pregnancy'
	| 'childbirth'

	// Social & Achievement
	| 'social'
	| 'achievement'

	// Support & Protection
	| 'helped'
	| 'common_interest'
	| 'outing'
	| 'defended'
	| 'crisis_together'
	| 'vulnerability'
	| 'shared_vulnerability'
	| 'entrusted';

/**
 * All valid subjects.
 */
export const SUBJECTS: readonly Subject[] = [
	// Conversation & Social
	'conversation',
	'confession',
	'argument',
	'negotiation',
	// Discovery & Information
	'discovery',
	'secret_shared',
	'secret_revealed',
	// Emotional
	'emotional',
	'emotionally_intimate',
	'supportive',
	'rejection',
	'comfort',
	'apology',
	'forgiveness',
	// Bonding & Connection
	'laugh',
	'gift',
	'compliment',
	'tease',
	'flirt',
	'date',
	'i_love_you',
	'sleepover',
	'shared_meal',
	'shared_activity',
	// Intimacy Levels
	'intimate_touch',
	'intimate_kiss',
	'intimate_embrace',
	'intimate_heated',
	// Sexual Activity
	'intimate_foreplay',
	'intimate_oral',
	'intimate_manual',
	'intimate_penetrative',
	'intimate_climax',
	// Action & Physical
	'action',
	'combat',
	'danger',
	// Decisions & Commitments
	'decision',
	'promise',
	'betrayal',
	'lied',
	// Life Events
	'exclusivity',
	'marriage',
	'pregnancy',
	'childbirth',
	// Social & Achievement
	'social',
	'achievement',
	// Support & Protection
	'helped',
	'common_interest',
	'outing',
	'defended',
	'crisis_together',
	'vulnerability',
	'shared_vulnerability',
	'entrusted',
] as const;

/**
 * Subject groups for UI display.
 */
export const SUBJECT_GROUPS = {
	conversation: ['conversation', 'confession', 'argument', 'negotiation'],
	discovery: ['discovery', 'secret_shared', 'secret_revealed'],
	emotional: [
		'emotional',
		'emotionally_intimate',
		'supportive',
		'rejection',
		'comfort',
		'apology',
		'forgiveness',
	],
	bonding: [
		'laugh',
		'gift',
		'compliment',
		'tease',
		'flirt',
		'date',
		'i_love_you',
		'sleepover',
		'shared_meal',
		'shared_activity',
	],
	intimacy_romantic: [
		'intimate_touch',
		'intimate_kiss',
		'intimate_embrace',
		'intimate_heated',
	],
	intimacy_sexual: [
		'intimate_foreplay',
		'intimate_oral',
		'intimate_manual',
		'intimate_penetrative',
		'intimate_climax',
	],
	action: ['action', 'combat', 'danger'],
	commitment: ['decision', 'promise', 'betrayal', 'lied'],
	life_events: ['exclusivity', 'marriage', 'pregnancy', 'childbirth'],
	social: ['social', 'achievement'],
	support: [
		'helped',
		'common_interest',
		'outing',
		'defended',
		'crisis_together',
		'vulnerability',
		'shared_vulnerability',
		'entrusted',
	],
} as const;

/**
 * Subjects that are considered "milestone-worthy" - significant enough
 * to generate a description when first occurring for a pair.
 */
export const MILESTONE_WORTHY_SUBJECTS: readonly Subject[] = [
	// Emotional milestones
	'confession',
	'emotionally_intimate',
	'forgiveness',
	// Bonding milestones
	'laugh',
	'gift',
	'compliment',
	'tease',
	'flirt',
	'date',
	'i_love_you',
	'sleepover',
	'shared_meal',
	'shared_activity',
	// Intimacy milestones
	'intimate_touch',
	'intimate_kiss',
	'intimate_embrace',
	'intimate_heated',
	// Sexual milestones
	'intimate_foreplay',
	'intimate_oral',
	'intimate_manual',
	'intimate_penetrative',
	'intimate_climax',
	// Life milestones
	'exclusivity',
	'marriage',
	'pregnancy',
	'childbirth',
	// Trust milestones
	'secret_shared',
	'promise',
	'betrayal',
	'helped',
	'defended',
	'crisis_together',
	'shared_vulnerability',
	'entrusted',
] as const;

/**
 * Type guard for valid subjects.
 */
export function isValidSubject(value: string): value is Subject {
	return SUBJECTS.includes(value as Subject);
}

/**
 * Check if a subject is milestone-worthy.
 */
export function isMilestoneWorthy(subject: Subject): boolean {
	return MILESTONE_WORTHY_SUBJECTS.includes(subject);
}

/**
 * Get the group a subject belongs to.
 */
export function getSubjectGroup(subject: Subject): string | null {
	for (const [group, subjects] of Object.entries(SUBJECT_GROUPS)) {
		if ((subjects as readonly string[]).includes(subject)) {
			return group;
		}
	}
	return null;
}
